### ISSUE TITLE
feat: Create the Footer

### ISSUE THREAD

**Issue by Min-Ho-Lim** [Min-Ho-Lim/Gym-Landing-Page#19]
# Acceptance Criteria:
1. Create a footer 
2. Add Company name, description, about, working hours, locations
3. Add social media icons to redirect

**Comment by MuhammadFahimulHuq** [comment]
Hello @Min-Ho-Lim. I want to contribute in this issue. Can you provide some idea or reference on how you want to layout the footer.

**Comment by Min-Ho-Lim** [comment]
There is no right or wrong layout. You can create something suitable footer.

![image](https://user-images.githubusercontent.com/13793276/207152162-201f7188-b346-46de-8ebe-4b53896c4ab2.png)
*Found on the internet (NOT MINE) - [Link](https://www.baamboostudio.com/weebly-design-inspiration-footer-design/)*

For your reference, I was going to create some thing like this. Of course, not exactly one to one copy, but you get the idea. 

Just keep it simple.

**Comment by Min-Ho-Lim** [comment]
@MuhammadFahimulHuq 
Are you still actively working on it? If not, I am going to create the footer section.

**Comment by MuhammadFahimulHuq** [comment]
Yes I am working on it. I will make a pull request by tomorrow.

**Comment by Min-Ho-Lim** [comment]
@MuhammadFahimulHuq Sounds good. Thanks for the reply.
Meanwhile, I will work on the other tickets.
