### ISSUE TITLE
feat: Add a loading screen

### ISSUE THREAD

**Issue by Min-Ho-Lim** [Min-Ho-Lim/Gym-Landing-Page#23]
Since we are going to add some videos and picture, we need a loading screen.

# Acceptance Criteria:
1. Create a loading screen
2. Loading screen will have a simple spinner and logo

**Comment by Rishav1707** [comment]
Shall I work on this issue? @Min-Ho-Lim

**Comment by Rishav1707** [comment]
But tell me what is the alignment of the spinner??
Where I have to place like centre, bottom, top etc.

**Comment by Min-Ho-Lim** [comment]
You may.
My initial thought was just a simple loading screen.

Like spinner in the center vertically horizontally and with loading message.

**Comment by Rishav1707** [comment]
@Min-Ho-Lim  Sorry, I am unable to solve this issue. Please assign this issue to someone.
Thank you for your patience.

**Comment by DonUggioni** [comment]
Hey is this still open? Can I work on this?

**Comment by Rishav1707** [comment]
Yes this issue is still open. You can work

**Comment by Min-Ho-Lim** [comment]
If you are working on the ticket, please assign yourself. Otherwise, I will treat it as no one is actively working on it.

**Comment by DonUggioni** [comment]
I don't know how to do that, sorry. Can you tell me how to do that?

**Comment by Min-Ho-Lim** [comment]
@DonUggioni Sorry for the inconvenience. Since I do not set up the assign permission, I guess I am the one who supposes to assign. I just assigned the ticket to you.
