### ISSUE TITLE
fix: Fix the mobile view horizontal oveflow

### ISSUE THREAD

**Issue by Min-Ho-Lim** [Min-Ho-Lim/Gym-Landing-Page#25]
![image](https://user-images.githubusercontent.com/13793276/207166438-3158a120-4590-4c63-aced-8a3f09d2911e.png)

Somehow, `Main` page causes another horizontal overflow.

# Acceptance Criteria:
1. Fix the horizontal overflow issue in `Main` page

**Comment by ebokes** [comment]
Hi @Min-Ho-Lim, my name is Chibu, I would love to work on this issue, please assign it to me

**Comment by Min-Ho-Lim** [comment]
Done. Thanks for your interests.
