### ISSUE TITLE
fix: Add key for lists to fix the unique key prop issue.

### ISSUE THREAD

**Issue by Min-Ho-Lim** [Min-Ho-Lim/Gym-Landing-Page#26]
![image](https://user-images.githubusercontent.com/13793276/207166736-7f4c5b53-258d-4ac3-8d5a-3a89e10a8c58.png)

Currently, `warning: Each child in a list should have a unique "key" prop.` is displaying in the console.
This is because some of lists are rendering without any key prop.
Add the unique prop for them.

# Acceptance Criteria:
1. Fix `warning: Each child in a list should have a unique "key" prop.` issue.

**Comment by Meldy2503** [comment]
Hi @Min-Ho-Lim, my name is Emelder, I would love to work on this issue, can you please assign it to me

**Comment by Meldy2503** [comment]
Hi @Min-Ho-Lim, my name is Emelder, I would love to work on this issue, please can you assign it to me

**Comment by Min-Ho-Lim** [comment]
Done. Thanks for your interests.
